/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.aman.sqlconectionproject;

import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author HP
 */
public class AddUpdateUser extends javax.swing.JFrame {

    Connection connection = Connection.getInstance();
    Boolean isUpdate = false;
    Users user = new Users();
    SimpleDateFormat simpleDateFormat = new SimpleDateFormat("dd/MM/yyyy");
    int id;
    /**
     * Creates new form SqlCrud
     */
    public AddUpdateUser() {
        initComponents();
        delete.setVisible(false);
        addUpdate.setText("Add User");
    }

    public AddUpdateUser(int id) {
        initComponents();
        isUpdate = true;
        String statement = "SELECT * FROM users WHERE id = " + id;
        try {
            PreparedStatement ps = connection.con.prepareStatement(statement);
            ResultSet resultSet = ps.executeQuery();
            while (resultSet.next()) {
                user.setId(resultSet.getInt("id"));
                user.setName(resultSet.getString("name"));
                user.setSclass(resultSet.getString("class"));
                user.setRollno(resultSet.getInt("rollno"));
                user.setDob(resultSet.getString("dob"));
                name.setText(resultSet.getString("name"));
                sclass.setText(resultSet.getString("class"));
                rollno.setText(String.valueOf(resultSet.getInt("rollno")));
                String dob = resultSet.getString("dob");
                Date selectedDate = simpleDateFormat.parse(dob);
                date.setDate(selectedDate);
                delete.setVisible(true);
                addUpdate.setText("Update User");
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddUpdateUser.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(AddUpdateUser.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        sclass = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rollno = new javax.swing.JTextField();
        addUpdate = new javax.swing.JButton();
        lblDate = new javax.swing.JLabel();
        date = new org.jdesktop.swingx.JXDatePicker();
        delete = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        menu.setText("menu");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("name");

        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameKeyTyped(evt);
            }
        });

        jLabel2.setText("class");

        sclass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sclassKeyTyped(evt);
            }
        });

        jLabel3.setText("rollno");

        rollno.setMinimumSize(new java.awt.Dimension(100, 22));
        rollno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rollnoKeyTyped(evt);
            }
        });

        addUpdate.setText("Add");
        addUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addUpdateMouseClicked(evt);
            }
        });

        lblDate.setText("date");

        delete.setText("Delete");
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDate, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name)
                    .addComponent(sclass)
                    .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                    .addComponent(rollno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(addUpdate)
                .addGap(84, 84, 84)
                .addComponent(delete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(name))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rollno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addUpdate)
                    .addComponent(delete))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addUpdateMouseClicked
        // TODO add your handling code here:
        if (name.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(name,
                    "Enter name",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        } else if (sclass.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(name,
                    "Enter class ",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        } else if (rollno.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(name,
                    "Enter rollno",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        } else if (isUpdate == true) {
            String sql = "UPDATE users set name=?, class=?, rollno=?, dob=? where id=?";

            PreparedStatement statement;
            try {
                String dob = simpleDateFormat.format(date.getDate());
                System.out.println("dob " + dob);
                statement = connection.con.prepareStatement(sql);
                statement.setString(1, name.getText().trim());
                statement.setString(2, sclass.getText().trim());
                statement.setInt(3, Integer.parseInt(rollno.getText().trim()));
                statement.setString(4, dob);
                statement.setInt(5, user.getId());

                int rowsInserted = statement.executeUpdate();
                if (rowsInserted > 0) {
                    System.out.println("A new user was inserted successfully!");
                    UsersList userList = new UsersList();
                    userList.setVisible(true);
                    this.dispose();

                }
            } catch (SQLException ex) {
                Logger.getLogger(AddUpdateUser.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            String sql = "INSERT INTO users (name, class, rollno, dob) VALUES (?, ?, ?, ?)";

            PreparedStatement statement;
            try {
                String dob = simpleDateFormat.format(date.getDate());
                System.out.println("dob " + dob);
                statement = connection.con.prepareStatement(sql);
                statement.setString(1, name.getText().trim());
                statement.setString(2, sclass.getText().trim());
                statement.setInt(3, Integer.parseInt(rollno.getText().trim()));
                statement.setString(4, dob);

                int rowsInserted = statement.executeUpdate();
                if (rowsInserted > 0) {
                    System.out.println("A new user was inserted successfully!");
                      UsersList userList = new UsersList();
                    userList.setVisible(true);
                    this.dispose();

                }
            } catch (SQLException ex) {
                Logger.getLogger(AddUpdateUser.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_addUpdateMouseClicked

    private void nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (((c < 'A') || (c > 'Z')) && ((c < 'a') || (c > 'z')) && (c != KeyEvent.VK_BACK_SPACE) && (c != KeyEvent.VK_SPACE)) {
            evt.consume();  // if it's not a number, ignore the event
        }
    }//GEN-LAST:event_nameKeyTyped

    private void sclassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sclassKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (((c < 'A') || (c > 'Z')) && ((c < 'a') || (c > 'z')) && (c != KeyEvent.VK_BACK_SPACE) && (c != KeyEvent.VK_SPACE)) {
            evt.consume();  // if it's not a number, ignore the event
        }
    }//GEN-LAST:event_sclassKeyTyped

    private void rollnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rollnoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
            evt.consume();  // if it's not a number, ignore the event
        }
    }//GEN-LAST:event_rollnoKeyTyped

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        // TODO add your handling code here:
         String sql = "DELETE FROM users where id = ?";

            PreparedStatement statement;
            try {
                statement = connection.con.prepareStatement(sql);
                statement.setInt(1, user.getId());

                int rowsInserted = statement.executeUpdate();
                if (rowsInserted > 0) {
                    System.out.println("A user is deleted");
                    UsersList userList = new UsersList();
                    userList.setVisible(true);
                    this.dispose();

                }
            } catch (SQLException ex) {
                Logger.getLogger(AddUpdateUser.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_deleteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        JTextField name = new JTextField();

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddUpdateUser().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUpdate;
    private org.jdesktop.swingx.JXDatePicker date;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JMenuItem menu;
    private javax.swing.JTextField name;
    private javax.swing.JTextField rollno;
    private javax.swing.JTextField sclass;
    // End of variables declaration//GEN-END:variables

}
